//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gw2_pluginUPtool_6.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 主程序 {
            get {
                return ((bool)(this["主程序"]));
            }
            set {
                this["主程序"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 流动输出 {
            get {
                return ((bool)(this["流动输出"]));
            }
            set {
                this["流动输出"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 配置板 {
            get {
                return ((bool)(this["配置板"]));
            }
            set {
                this["配置板"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 小提示 {
            get {
                return ((bool)(this["小提示"]));
            }
            set {
                this["小提示"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 团队力学 {
            get {
                return ((bool)(this["团队力学"]));
            }
            set {
                this["团队力学"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 团队恩赐 {
            get {
                return ((bool)(this["团队恩赐"]));
            }
            set {
                this["团队恩赐"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 坐骑插件 {
            get {
                return ((bool)(this["坐骑插件"]));
            }
            set {
                this["坐骑插件"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dx12 {
            get {
                return ((bool)(this["dx12"]));
            }
            set {
                this["dx12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool r滤镜 {
            get {
                return ((bool)(this["r滤镜"]));
            }
            set {
                this["r滤镜"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool s滤镜 {
            get {
                return ((bool)(this["s滤镜"]));
            }
            set {
                this["s滤镜"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 启动_ {
            get {
                return ((bool)(this["启动_"]));
            }
            set {
                this["启动_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 跳过_ {
            get {
                return ((bool)(this["跳过_"]));
            }
            set {
                this["跳过_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 开启_ {
            get {
                return ((bool)(this["开启_"]));
            }
            set {
                this["开启_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 附加_ {
            get {
                return ((bool)(this["附加_"]));
            }
            set {
                this["附加_"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 首次运行检测 {
            get {
                return ((bool)(this["首次运行检测"]));
            }
            set {
                this["首次运行检测"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gw2sy.top/d3d9.dll")]
        public string 主程序_地址 {
            get {
                return ((string)(this["主程序_地址"]));
            }
            set {
                this["主程序_地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gw2sy.top/wp-content/uploads/d3d9_arcdps_buildpad.dll")]
        public string 配置板_地址 {
            get {
                return ((string)(this["配置板_地址"]));
            }
            set {
                this["配置板_地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gw2sy.top/wp-content/uploads/d3d9_arcdps_ct.dll")]
        public string 小提示_地址 {
            get {
                return ((string)(this["小提示_地址"]));
            }
            set {
                this["小提示_地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gw2sy.top//wp-content/uploads/d3d9_arcdps_sct.dll")]
        public string 流动输出_地址 {
            get {
                return ((string)(this["流动输出_地址"]));
            }
            set {
                this["流动输出_地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gw2sy.top//wp-content/uploads/d3d9_arcdps_mechanicschs.dll")]
        public string 团队力学_地址 {
            get {
                return ((string)(this["团队力学_地址"]));
            }
            set {
                this["团队力学_地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gw2sy.top//wp-content/uploads/d3d9_arcdps_tablechs.dll")]
        public string 团队恩赐_地址 {
            get {
                return ((string)(this["团队恩赐_地址"]));
            }
            set {
                this["团队恩赐_地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gw2sy.top//wp-content/uploads/d3d9_ReShade641.zip")]
        public string r滤镜_地址 {
            get {
                return ((string)(this["r滤镜_地址"]));
            }
            set {
                this["r滤镜_地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gw2sy.top//wp-content/uploads/SweetFX.zip")]
        public string s滤镜_地址 {
            get {
                return ((string)(this["s滤镜_地址"]));
            }
            set {
                this["s滤镜_地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gw2sy.top//wp-content/uploads/arcdps_lang.ini")]
        public string 汉化文件地址 {
            get {
                return ((string)(this["汉化文件地址"]));
            }
            set {
                this["汉化文件地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d912pxy_v1.4_r367.zip")]
        public string dx12文件名 {
            get {
                return ((string)(this["dx12文件名"]));
            }
            set {
                this["dx12文件名"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gw2sy.top//wp-content/uploads/d3d9_chainload.dll")]
        public string 坐骑插件_地址 {
            get {
                return ((string)(this["坐骑插件_地址"]));
            }
            set {
                this["坐骑插件_地址"] = value;
            }
        }
    }
}
